services:
  nx-app:
    build:
      context: .
      dockerfile: resources/docker/Dockerfile
    ports:
      - "3000:80"
    container_name: nx-mod-rspack-app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 